version: '3.8'

services:
  frontend:
    image: 029054246266.dkr.ecr.us-east-1.amazonaws.com/owntrack-frontend:latest
    ports:
      - "80:80"
    environment:
      - SERVER_HOST=recorder
      - SERVER_PORT=8083
    depends_on:
      - recorder
    networks:
      - owntracks-net
    restart: always

  mqtt:
    image: 029054246266.dkr.ecr.us-east-1.amazonaws.com/owntrack-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
    networks:
      - owntracks-net
    restart: always

  recorder:
    image: 029054246266.dkr.ecr.us-east-1.amazonaws.com/owntrack-recorder:latest
    ports:
      - "8083:8083"
    environment:
      - OTR_HOST=mqtt
      - OTR_GEOKEY=opencage:87ff6da9fff542079ae30a28a36a4ade
    volumes:
      - recorder-store:/store
    depends_on:
      - mqtt
    networks:
      - owntracks-net
    restart: always

volumes:
  recorder-store:
  mqtt-data:
  mqtt-log:

networks:
  owntracks-net:
    driver: bridge
